# Generated by Django 5.2.7 on 2025-10-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='Concluída'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tarefas', to='tarefas.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['created_at'], name='tarefa_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['prioridade'], name='tarefa_prioridade_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['completed_at'], name='tarefa_completed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['categoria'], name='tarefa_categoria_idx'),
        ),
    ]
